#!/usr/bin/env ruby

if ARGV.empty?
  STDERR.puts "You need to provide a URL"
  STDERR.puts "USAGE: #{$0} [url]"
end

%w{rubygems tumblr}.each {|f| require f }

posts       = []
tumblr_url  = ARGV[0]

  Tumblr::API.read(tumblr_url) do |pager|
    pager.last_page.times do |page_number|
      current_page = pager.page(page_number)
      current_page.posts.each do |p| 
        puts p.inspect
        posts << p
      end
    end
  end


puts "Success: found #{posts.length} posts"
